---
- name: Prepare
  hosts: all
  gather_facts: false
  remote_user: root
  tasks:
    - name: Ensure python
      ansible.builtin.raw: apt-get update
      changed_when: false
    - name: Ensure python
      ansible.builtin.raw: DEBIAN_FRONTEND=noninteractive apt-get install -y python3.9
      changed_when: false

- name: Deploy
  hosts: all
  remote_user: root
  vars:
    prerequisites:
      - tar
      - unzip
      - curl
    consul_version: 1.15.0
    consul_arch:
      x86_64: amd64
      aarch64: arm64
    consul_data_dir: "/opt/consul"
    server_encrypt_key: "."
    tini_version: v0.19.0
    tini_arch:
      x86_64: amd64
      aarch64: arm64
      armv6l: armel
  tasks:
    - name: Ensure Prerequisites
      ansible.builtin.package:
        name: "{{ prerequisites }}"
        state: present
    - name: Get Consul
      ansible.builtin.unarchive:
        src: "https://releases.hashicorp.com/consul/{{ consul_version }}/consul_{{ consul_version }}_linux_{{ consul_arch[ansible_architecture] }}.zip"
        dest: /bin/
        remote_src: true
        mode: "0777"
        owner: root
        group: root
    - name: Add Consul group
      ansible.builtin.group:
        name: consul
        state: present
    - name: Add Consul user
      ansible.builtin.user:
        name: consul
        group: consul
        groups: consul
        append: true
        state: present
    - name: Add configuration directory
      ansible.builtin.file:
        path: /etc/consul.d
        state: directory
        recurse: true
        mode: "0644"
        owner: consul
        group: consul
    - name: Create Consul configuration
      ansible.builtin.template:
        src: consul.hcl.j2
        dest: /etc/consul.d/consul.hcl
        backup: true
        mode: "0644"
        owner: consul
        group: consul
        variable_start_string: "[["
        variable_end_string: "]]"
    - name: Get Tini
      ansible.builtin.get_url:
        url: "https://github.com/krallin/tini/releases/download/{{ tini_version }}/tini-{{ tini_arch[ansible_architecture] }}"
        dest: "/tini"
        mode: "0777"
        owner: root
        group: root
