---
- name: Prepare
  hosts: all
  gather_facts: false
  remote_user: root
  tasks:
    # - name: Update cache
    #   ansible.builtin.raw: apt-get update
    #   changed_when: false
    - name: Ensure python
      ansible.builtin.raw: apk add python3
      changed_when: false

- name: Deploy
  hosts: all
  remote_user: root
  vars:
    prerequisites:
      - tar
      - unzip
      - curl
      - tini
    consul_arch:
      x86_64: amd64
      aarch64: arm64
    consul_data_dir: "/opt/consul"
  tasks:
    - name: Ensure Prerequisites
      ansible.builtin.package:
        name: "{{ prerequisites }}"
        state: present
    - name: Get Consul
      ansible.builtin.unarchive:
        src: "https://releases.hashicorp.com/consul/{{ consul_version }}/consul_{{ consul_version }}_linux_{{ consul_arch[ansible_architecture] }}.zip"
        dest: /bin/
        remote_src: true
        mode: "0777"
        owner: root
        group: root
    - name: Add Consul group
      ansible.builtin.group:
        name: consul
        state: present
    - name: Add Consul user
      ansible.builtin.user:
        name: consul
        group: consul
        groups: consul
        append: true
        state: present
    - name: Add configuration directory
      ansible.builtin.file:
        path: /etc/consul.d
        state: directory
        recurse: true
        mode: "0775"
        owner: consul
        group: consul
    - name: Create Consul configuration
      ansible.builtin.template:
        src: consul.hcl.j2
        dest: /etc/consul.d/consul.hcl
        backup: true
        mode: "0644"
        owner: consul
        group: consul
        variable_start_string: "[["
        variable_end_string: "]]"
    - name: Ensure data dir is writable
      ansible.builtin.file:
        path: /opt/consul
        state: directory
        owner: consul
        group: consul
        mode: "0775"
- name: Remove Python3
  hosts: all
  tasks:
    - name: Ensure python is absent
      ansible.builtin.package:
        name: python3
        state: absent
