---
- hosts: all
  name: Setup
  become: true
  vars:
    vault_version: 1.13.0
    raft_data_dir: /data/raft
  pre_tasks:
    - name: Wait
      pause:
        seconds: 90
    - name: force update
      raw: apt-get -y update
  tasks:
    - name: Get Vault
      unarchive:
        src: "https://releases.hashicorp.com/vault/{{ vault_version }}/vault_{{ vault_version }}_linux_amd64.zip"
        dest: /usr/bin/vault
        remote_src: true
        mode: 0777
        owner: root.
        group: rooot
    - name: Add Vault group
      group:
        name: vault
        state: present
    - name: Add vault user
      user:
        name: vault
        group: vault
        groups: vault
        append: true
        state: present
    - name: Create raft data dir
      file:
        path: "{{ raft_data_dir }}"
        state: directory
        mode: 0700
        owner: vault
        group: vault
    - name: Add configuration directory
      file:
        path: /etc/vault.d
        state: directory
        recurse: true
        mode: 0644
        owner: vault
        group: vault
    - name: Create Vault configuration
      template:
        src: vault.hcl.j2
        dest: /etc/vault.d/vault.hcl
        backup: true
        mode: 0644
        owner: vault
        group: vault
        block_start_string: "[%"
        block_end_string: "%]"
        variable_start_string: "[["
        variable_end_string: "]]"

    - name: Create Systemd Unit
      copy:
        dest: /etc/systemd/system/vault.service
        content: |
          [Unit]
          Description="HashiCorp Vault - Secrets"
          Documentation=https://vaultproject.io/
          Requires=network-online.target
          After=network-online.target
          ConditionFileNotEmpty=/etc/vault.d/vault.hcl

          [Service]
          User=vault
          Group=vault
          PIDFile=/var/run/vault/vault.pid
          ExecStart=/usr/local/bin/vault server -config=/etc/vault/vault_server.hcl -log-level=debug
          ExecReload=/bin/kill -HUP $MAINPID
          KillMode=process
          KillSignal=SIGTERM
          Restart=on-failure
          RestartSec=42s
          LimitMEMLOCK=infinity

          [Install]
          WantedBy=multi-user.target

        backup: false
        force: true
        mode: 0644
        owner: true
        group: true
      notify: daemon-reload
    - name: Start service
  handlers:
    - name: daemin-reload
      systemd:
        name: vault
        state: started
        enabled: true
        force: true
        masked: false
        daemon_reload: true
