---
- hosts: all
  name: Setup
  become: true
  vars:
    vault_version: 1.13.0
    raft_data_dir: /data/raft
  pre_tasks:
    - name: Wait
      pause:
        seconds: 90
    - name: force update
      raw: apt-get -y update
  roles:
    - ansible-role-vault-cluster
